import type { UnifiedProvider } from './types.js'

// All 5 tool types for convenience
const ALL_TOOLS = ['claude-code', 'codex', 'gemini-cli', 'opencode', 'openclaw'] as const
const OPENAI_COMPAT = ['claude-code', 'codex', 'opencode', 'openclaw'] as const
const CLAUDE_ONLY = ['claude-code'] as const

// =============================================================================
// China Region Providers
// =============================================================================

const cnProviders: UnifiedProvider[] = [
  {
    id: '302ai',
    name: '302.AI',
    apiUrl: 'https://api.302.ai',
    authType: 'api_key',
    supportedTools: [...ALL_TOOLS],
    description: 'Multi-model gateway, supports Claude/GPT/Gemini',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    apiUrl: 'https://api.siliconflow.cn/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'High-performance inference platform',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    apiUrl: 'https://api.deepseek.com',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'deepseek-chat' },
    description: 'DeepSeek V3/R1 models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    apiUrl: 'https://api.moonshot.cn/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'moonshot-v1-128k' },
    description: 'Long-context models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    apiUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'glm-4-plus' },
    description: 'GLM-4 series',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'baichuan',
    name: 'Baichuan',
    apiUrl: 'https://api.baichuan-ai.com/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'Baichuan4' },
    description: 'Baichuan large models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    apiUrl: 'https://api.minimax.chat/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'abab6.5s-chat' },
    description: 'MiniMax ABAB models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'yi',
    name: '01.AI (Yi)',
    apiUrl: 'https://api.lingyiwanwu.com/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'yi-lightning' },
    description: 'Yi series models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    apiUrl: 'https://api.stepfun.com/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'step-2-16k' },
    description: 'Step series models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'spark',
    name: 'iFlytek Spark',
    apiUrl: 'https://spark-api-open.xf-yun.com/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'spark-max' },
    description: 'Spark large models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'qwen',
    name: 'Alibaba Qwen (DashScope)',
    apiUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'qwen-max' },
    description: 'Qwen series via DashScope',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'hunyuan',
    name: 'Tencent Hunyuan',
    apiUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'hunyuan-pro' },
    description: 'Hunyuan large models',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'ernie',
    name: 'Baidu ERNIE',
    apiUrl: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop',
    authType: 'auth_token',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'ernie-4.0-8k' },
    description: 'ERNIE Bot series',
    region: 'CN',
    openaiCompatible: false,
  },
  {
    id: 'doubao',
    name: 'ByteDance Doubao (Ark)',
    apiUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'doubao-pro-128k' },
    description: 'Doubao models via Volcano Ark',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'oneapi',
    name: 'OneAPI (Self-hosted)',
    apiUrl: 'http://localhost:3000/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Self-hosted multi-model gateway',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'newapi',
    name: 'NewAPI (Self-hosted)',
    apiUrl: 'http://localhost:3001/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'OneAPI fork with enhanced features',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'openrouter-cn',
    name: 'OpenRouter (CN Mirror)',
    apiUrl: 'https://openrouter.ai/api/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'OpenRouter via CN proxy',
    region: 'CN',
    openaiCompatible: true,
  },
  {
    id: 'cloudflare-ai-cn',
    name: 'Cloudflare Workers AI',
    apiUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Cloudflare edge inference',
    region: 'CN',
    openaiCompatible: true,
  },
]

// =============================================================================
// Global Region Providers
// =============================================================================

const globalProviders: UnifiedProvider[] = [
  {
    id: 'anthropic',
    name: 'Anthropic (Official)',
    apiUrl: 'https://api.anthropic.com',
    authType: 'api_key',
    supportedTools: [...CLAUDE_ONLY],
    models: {
      default: 'claude-sonnet-4-20250514',
      haiku: 'claude-haiku-4-5-20251001',
      sonnet: 'claude-sonnet-4-20250514',
      opus: 'claude-opus-4-20250514',
    },
    description: 'Official Claude API',
    region: 'Global',
    openaiCompatible: false,
  },
  {
    id: 'openai',
    name: 'OpenAI (Official)',
    apiUrl: 'https://api.openai.com/v1',
    authType: 'api_key',
    supportedTools: ['codex', 'opencode', 'openclaw'],
    models: { default: 'gpt-4o' },
    description: 'Official GPT API',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'google-ai',
    name: 'Google AI Studio',
    apiUrl: 'https://generativelanguage.googleapis.com/v1beta',
    authType: 'api_key',
    supportedTools: ['gemini-cli'],
    models: { default: 'gemini-2.0-flash' },
    description: 'Official Gemini API',
    region: 'Global',
    openaiCompatible: false,
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    apiUrl: 'https://{resource}.openai.azure.com/openai/deployments/{deployment}',
    authType: 'api_key',
    supportedTools: ['codex', 'opencode', 'openclaw'],
    description: 'Azure-hosted OpenAI models',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    apiUrl: 'https://bedrock-runtime.{region}.amazonaws.com',
    authType: 'auth_token',
    supportedTools: [...CLAUDE_ONLY],
    models: {
      default: 'anthropic.claude-sonnet-4-20250514-v1:0',
      sonnet: 'anthropic.claude-sonnet-4-20250514-v1:0',
      opus: 'anthropic.claude-opus-4-20250514-v1:0',
    },
    description: 'Claude via AWS Bedrock',
    region: 'Global',
    openaiCompatible: false,
  },
  {
    id: 'google-vertex',
    name: 'Google Cloud Vertex AI',
    apiUrl: 'https://{region}-aiplatform.googleapis.com/v1',
    authType: 'auth_token',
    supportedTools: ['claude-code', 'gemini-cli'],
    description: 'Claude & Gemini via Vertex AI',
    region: 'Global',
    openaiCompatible: false,
  },
  {
    id: 'together',
    name: 'Together AI',
    apiUrl: 'https://api.together.xyz/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'meta-llama/Llama-3-70b-chat-hf' },
    description: 'Open-source model hosting',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'groq',
    name: 'Groq',
    apiUrl: 'https://api.groq.com/openai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'llama-3.1-70b-versatile' },
    description: 'Ultra-fast LPU inference',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    apiUrl: 'https://api.fireworks.ai/inference/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'accounts/fireworks/models/llama-v3p1-70b-instruct' },
    description: 'Fast generative AI inference',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    apiUrl: 'https://openrouter.ai/api/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Unified API for 100+ models',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    apiUrl: 'https://api.perplexity.ai',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'sonar-pro' },
    description: 'Search-augmented models',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    apiUrl: 'https://api.mistral.ai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'mistral-large-latest' },
    description: 'Mistral & Mixtral models',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    apiUrl: 'https://api.cohere.com/v2',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'command-r-plus' },
    description: 'Command R series',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    apiUrl: 'https://api.replicate.com/v1',
    authType: 'auth_token',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Run open-source models',
    region: 'Global',
    openaiCompatible: false,
  },
  {
    id: 'anyscale',
    name: 'Anyscale Endpoints',
    apiUrl: 'https://api.endpoints.anyscale.com/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'meta-llama/Meta-Llama-3-70B-Instruct' },
    description: 'Scalable model serving',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'lepton',
    name: 'Lepton AI',
    apiUrl: 'https://api.lepton.ai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Fast model inference',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    apiUrl: 'https://api.deepinfra.com/v1/openai',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'meta-llama/Meta-Llama-3-70B-Instruct' },
    description: 'Fast serverless inference',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    apiUrl: 'https://api.sambanova.ai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'Meta-Llama-3.1-70B-Instruct' },
    description: 'SambaNova Cloud inference',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    apiUrl: 'https://api.cerebras.ai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'llama3.1-70b' },
    description: 'Wafer-scale chip inference',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'litellm',
    name: 'LiteLLM (Self-hosted)',
    apiUrl: 'http://localhost:4000/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Self-hosted model proxy',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    apiUrl: 'http://localhost:11434/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'llama3.1' },
    description: 'Local model runner',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (Local)',
    apiUrl: 'http://localhost:1234/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Local model GUI',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'vllm',
    name: 'vLLM (Self-hosted)',
    apiUrl: 'http://localhost:8000/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'High-throughput serving engine',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI',
    apiUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'Edge AI inference',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference',
    apiUrl: 'https://api-inference.huggingface.co/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    description: 'HF model inference endpoints',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    apiUrl: 'https://integrate.api.nvidia.com/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'meta/llama-3.1-70b-instruct' },
    description: 'NVIDIA inference microservices',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    apiUrl: 'https://api.x.ai/v1',
    authType: 'api_key',
    supportedTools: [...OPENAI_COMPAT],
    models: { default: 'grok-2' },
    description: 'Grok models',
    region: 'Global',
    openaiCompatible: true,
  },
  {
    id: 'custom',
    name: 'Custom Provider',
    apiUrl: '',
    authType: 'api_key',
    supportedTools: [...ALL_TOOLS],
    description: 'Custom OpenAI-compatible endpoint',
    region: 'Global',
    openaiCompatible: true,
  },
]

// =============================================================================
// Exports
// =============================================================================

/** All provider presets */
export const PROVIDER_PRESETS: UnifiedProvider[] = [...cnProviders, ...globalProviders]

/** Get providers grouped by region */
export function getProvidersByRegion(): Record<'CN' | 'Global', UnifiedProvider[]> {
  return {
    CN: cnProviders,
    Global: globalProviders,
  }
}

/** Find a provider by id (exact match) */
export function findProvider(id: string): UnifiedProvider | undefined {
  return PROVIDER_PRESETS.find(p => p.id === id)
}

/**
 * Find a provider by fuzzy match — case-insensitive on id or name.
 * Useful for CLI flags like --provider "302ai" or --provider "DeepSeek".
 */
export function findProviderFuzzy(query: string): UnifiedProvider | undefined {
  const q = query.toLowerCase().trim()
  // First try: exact id match (already handled by findProvider, but keep for safety)
  const byId = PROVIDER_PRESETS.find(p => p.id.toLowerCase() === q)
  if (byId) return byId
  // Second: name contains query
  const byName = PROVIDER_PRESETS.find(p => p.name.toLowerCase().includes(q))
  if (byName) return byName
  // Third: query contains provider id (e.g., "deepseek-v3" → id "deepseek")
  return PROVIDER_PRESETS.find(p => q.includes(p.id.toLowerCase()))
}

/** Get providers that support a specific tool */
export function getProvidersForTool(tool: string): UnifiedProvider[] {
  return PROVIDER_PRESETS.filter(p => p.supportedTools.includes(tool as any))
}
